### ISSUE TITLE
Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA

### ISSUE THREAD

**Issue by sultan99** [jaydenseric/graphql-upload#133]
Hi @jaydenseric!
Thank you for the great efforts to make this library.

I'm using `apollo-server v2.3.1` which includes `graphql-upload` under hood.
I get the error when I'm trying to stream image file from client to another http mecro-service:
```bash
BadRequestError: Request disconnected during file upload stream parsing.
    at IncomingMessage.request.once (C:\omr-qraphql\node_modules\graphql-upload\lib\processRequest.js:245:35)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:182:13)
    at resOnFinish (_http_server.js:564:7)
    at ServerResponse.emit (events.js:187:15)
    at onFinish (_http_outgoing.js:683:10)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at FormData.CombinedStream._emitError (C:\omr-qraphql\node_modules\combined-stream\lib\combined_stream.js:188:8)
    at DelayedStream.<anonymous> (C:\omr-qraphql\node_modules\combined-stream\lib\combined_stream.js:114:10)
    at DelayedStream.emit (events.js:182:13)
    at DelayedStream._handleEmit (C:\omr-qraphql\node_modules\delayed-stream\lib\delayed_stream.js:82:15)
    at ReadStream.source.emit (C:\omr-qraphql\node_modules\delayed-stream\lib\delayed_stream.js:29:19)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I'm using form-data to send http request:
```js
import FormData from 'form-data'

async upload(templateId, file) {
  const {createReadStream, filename} = await file
  return new Promise((resolve, reject) => {
    const form = new FormData()
    form.append(`templateId`, templateId)
    form.append(`file`, createReadStream())
    form.append(`filename`, filename)
    form.submit(`http://localhost:3001/v1/worksheets`,
      (err, res) => err ? reject(err) : resolve(res)
    )
  })
}
```

Here is my resolver:
```js
Mutation: {
  uploadAnswerSheet: async (root, {templateId, file}) => (
    upload(templateId, file)
  )
}
```

And this error I get on `http://localhost:3001/v1/worksheets`:
```bash
Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA
    at MultipartParser.end (C:\omr-kernel-api\node_modules\formidable\lib\multipart_parser.js:326:12)
    at IncomingMessage.<anonymous> (C:\omr-kernel-api\node_modules\formidable\lib\incoming_form.js:132:30)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

When I save file from the stream at graphql server and send it using `fs.createReadStream` it works perfect. I want just stream the data without saving it on graphql server.
I don't  know where to dig, I have tried many combinations, looks like `createReadStream` not same as `fs.createReadStream`.

**Comment by mike-marcacci** [comment]
Hi @sultan99, sorry for the delay – not sure why but I never got a notification from GitHub when you submitted this issue.

Just to be clear, when you pipe the contents of `createReadStream()` into a file, and then use `form.append(`file, fs.createReadStream(thePath))`, it works?

**Comment by sultan99** [comment]
> Hi @sultan99, sorry for the delay – not sure why but I never got a notification from GitHub when you submitted this issue.
> 
> Just to be clear, when you pipe the contents of `createReadStream()` into a file, and then use `form.append('file', fs.createReadStream(pathToTheNewFile))`, it works?
Yes it works. But directly streaming not working.
