### ISSUE TITLE
Node 14 support

### ISSUE THREAD

**Issue by gregaou** [jaydenseric/graphql-upload#210]
When using graphql-upload with Node 14, i get the same issue as this comment concerning Node 14 support (https://github.com/jaydenseric/graphql-upload/issues/170#issuecomment-633263845_)

```json
{
   "code":"INTERNAL_SERVER_ERROR",
   "exception":{
      "stacktrace":[
         "RangeError: Maximum call stack size exceeded",
         "    at ReadStream.deprecated [as open] (internal/util.js:74:22)",
         "    at ReadStream.open (/path/of/my/project/node_modules/apollo-server-core/node_modules/fs-capacitor/lib/index.js:90:11)",
         "    at _openReadFs (internal/fs/streams.js:153:12)",
         "    at ReadStream.<anonymous> (internal/fs/streams.js:146:3)",
         "    at ReadStream.deprecated [as open] (internal/util.js:89:15)",
         "    at ReadStream.open (/path/of/my/project/node_modules/apollo-server-core/node_modules/fs-capacitor/lib/index.js:90:11)",
         "    at _openReadFs (internal/fs/streams.js:153:12)",
         "    at ReadStream.<anonymous> (internal/fs/streams.js:146:3)",
         "    at ReadStream.deprecated [as open] (internal/util.js:89:15)",
         "    at ReadStream.open (/path/of/my/project/node_modules/apollo-server-core/node_modules/fs-capacitor/lib/index.js:90:11)",
         "    at _openReadFs (internal/fs/streams.js:153:12)",
         "    at ReadStream.<anonymous> (internal/fs/streams.js:146:3)",
         "    at ReadStream.deprecated [as open] (internal/util.js:89:15)",
         "    at ReadStream.open (/path/of/my/project/node_modules/apollo-server-core/node_modules/fs-capacitor/lib/index.js:90:11)",
         "    at _openReadFs (internal/fs/streams.js:153:12)",
         "    at ReadStream.<anonymous> (internal/fs/streams.js:146:3)"
      ]
   }
}
```

Any workarounds/solutions with Node 14 ?

**Comment by jaydenseric** [comment]
If you run `npm ls graphql-upload`, what version appears? Is there only one installation, or a few?

**Comment by jaydenseric** [comment]
Closing because I'm quite sure you’re using an out of date version. This package is tested in Node.js v14 and all tests pass:

https://github.com/jaydenseric/graphql-upload/runs/705152624?check_suite_focus=true#step:4:136
