### ISSUE TITLE
I get this error when I try to upload a file with apollo-server , The file is loaded in the public/images folder, where I want it to be, but it is corrupt and does not open  

### ISSUE THREAD

**Issue by chadjaa-sofiane** [jaydenseric/graphql-upload#229]
RangeError: Maximum call stack size exceeded
    at ReadStream.open (C:\Users\sofia\OneDrive\Bureau\project\backend\node_modules\apollo-server-core\node_modules\fs-capacitor\lib\index.js:80:7)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\sofia\OneDrive\Bureau\project\backend\node_modules\apollo-server-core\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\sofia\OneDrive\Bureau\project\backend\node_modules\apollo-server-core\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\sofia\OneDrive\Bureau\project\backend\node_modules\apollo-server-core\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chadjaa-sofiane** [comment]
the code I use

import { UserInputError } from "apollo-server";
import { createWriteStream } from "fs";
import { join } from "path";
const MIME_TYPES = {
  "image/jpg": "jpg",
  "image/jpeg": "jpg",
  "image/png": "png",
};
const storeUpload = async ({ stream, filename, mimetype }) => {
  const originalname = filename.split(" ").join("_").split(".")[0];
  const extension = MIME_TYPES[mimetype];
  if (!extension)
    throw new UserInputError("file Type not allowed", {
      errors: "fileType not allowed",
    });
  const path = join(
    __dirname,
    `../public/images/${originalname}_${Date.now()}.${extension}`
  );
  return new Promise((resolve, reject) =>
    stream
      .pipe(createWriteStream(path))
      .on("finish", () => resolve({ id, path, filename, mimetype }))
      .on("error", reject)
  );
};

export const processUpload = async (upload) => {
  const { createReadStream, filename, mimetype } = await upload;
  const stream = createReadStream();
  const file = await storeUpload({ stream, filename, mimetype });
  return file;
};

**Comment by jaydenseric** [comment]
You are using the outdated `graphql-upload` version that Apollo Server is using. Please use the latest version, and direct any Apollo Server support queries to Apollo's repos.

Also, please format code nicely in issues or comments on GitHub so we can easily read what you share.

```js
// This code is syntax highlighted, and tidilly formatted.
function hello () {
  console.log('Hello world.');
}
```
