### ISSUE TITLE
There can be only one type named "Upload"

### ISSUE THREAD

**Issue by sittingbool** [jaydenseric/graphql-upload#240]
Hi, I would like to use this with the following setup:

- express server
- apollo-server-express
- type-graphql
- package.json-dependencies: 
```
  "dependencies": {
    "@types/express-serve-static-core": "^4.17.18",
    "apollo-server-express": "^2.21.1",
    "apollo-server-testing": "^2.21.1",
    "bcrypt": "^5.0.0",
    "body-parser": "^1.19.0",
    "class-validator": "^0.13.1",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "email-templates": "^8.0.3",
    "express": "^4.17.1",
    "fastest-validator": "^1.9.0",
    "graphql": "^15.5.0",
    "graphql-upload": "^11.0.0",
    "lodash": "^4.17.20",
    "mkdirp": "^1.0.4",
    "sb-util-ts": "^2.8.0",
    "sharp": "^0.27.2",
    "socket-controllers": "0.0.5",
    "socket.io": "^3.1.0",
    "string-similarity": "^4.0.4",
    "type-graphql": "^1.1.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@testdeck/mocha": "^0.1.2",
    "@types/bcrypt": "^3.0.0",
    "@types/body-parser": "^1.19.0",
    "@types/chai": "^4.2.14",
    "@types/chai-http": "^4.2.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/cors": "^2.8.9",
    "@types/email-templates": "^8.0.0",
    "@types/express": "^4.17.11",
    "@types/lodash": "^4.14.168",
    "@types/mkdirp": "^1.0.1",
    "@types/mocha": "^8.2.0",
    "@types/node": "^14.14.22",
    "@types/pug": "^2.0.4",
    "@types/sharp": "^0.27.1",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "chai": "^4.2.0",
    "chai-http": "^4.3.0",
    "eslint": "^7.18.0",
    "husky": "^4.3.8",
    "js-sha512": "^0.8.0",
    "lint-staged": "^10.5.3",
    "mocha": "^8.2.1",
    "pug": "^3.0.2",
    "typescript": "^4.0.5"
  }, 
```
(**WEIRD**: I had to add graphql-upload in dependencies but every tutorial says it should be part of apollo server)

Code in resolver:

```
import { GraphQLUpload, FileUpload } from 'graphql-upload';

...

@Mutation(returns => UserModel)
uploadUserAvatar(@Arg('file', () => GraphQLUpload) file: FileUpload) {
```

Once I start up the server I am getting an error:

```
Error: There can be only one type named "Upload".
    at assertValidSDL (/path/to/my/project/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/path/to/my/project/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at Object.buildSchemaFromTypeDefinitions (/path/to/my/project/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at Object.makeExecutableSchema (/path/to/my/project/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at ApolloServer.initSchema (/path/to/my/project/node_modules/apollo-server-core/dist/ApolloServer.js:264:49)
    at new ApolloServerBase (/path/to/my/project/node_modules/apollo-server-core/dist/ApolloServer.js:159:30)
    at new ApolloServer (/path/to/my/project/node_modules/apollo-server-express/dist/ApolloServer.js:60:9)
    at createApolloServer (/path/to/my/project/app/api/api.js:79:20)
    at /path/to/my/project/app/api/api.js:67:9
```

Does anyone know how to solve this?

**Comment by jaydenseric** [comment]
Apollo Server ships with an outdated version of `graphql-upload`; you need to disable their implementation and setup the current version of `graphql-upload` yourself, otherwise the two `graphql-upload` integrations will conflict. Please refer to Apollo for support with their products.

**Comment by geoyws** [comment]
![image](https://user-images.githubusercontent.com/1738396/115859659-1373b600-a463-11eb-8267-37161a076334.png)

Also, if you are using a monorepo, make sure that all `graphql-upload` versions are similar, otherwise `Upload` will be registered twice. Just encountered that this afternoon.
