### ISSUE TITLE
Uploading file crashes application when built with webpack

### ISSUE THREAD

**Issue by ziggy6792** [jaydenseric/graphql-upload#258]
Hi

I am trying to use `graphql-upload` in a typescript app built with webpack.

### My setup

- Typescript app
- Apollo server / Typegraphql
- Build with webpack

### My Code
(stripped down to the essentials)

https://github.com/ziggy6792/graphql-file-uploads 

### My Problem

When I run with ts-node `yarn start:ts:node` then run `yarn test` an image gets uploaded no problem

But then I build with webpack `yarn start` then run `yarn test` I get the following error

```
/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:56105
            if (!isObject(operations) && !Array.isArray(operations))
                 ^

TypeError: isObject is not a function
    at Busboy.<anonymous> (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:56105:18)
    at Busboy.emit (node:events:378:20)
    at Busboy.module.exports../node_modules/busboy/lib/main.js.Busboy.emit (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:32204:33)
    at PartStream.onEnd (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:32528:15)
    at PartStream.emit (node:events:390:22)
    at Dicer.onPart (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:32386:13)
    at Dicer.emit (node:events:378:20)
    at Dicer.module.exports../node_modules/dicer/lib/Dicer.js.Dicer.emit (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:45439:35)
    at Dicer.module.exports../node_modules/dicer/lib/Dicer.js.Dicer._oninfo (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:45540:12)
    at SBMH.<anonymous> (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:45486:10)
[nodemon] app crashed - waiting for file changes before starting...
```

### My Attempts to solve

Sorry I am not sure if this actually a problem with `graphql-upload` or `webpack` or something else. I also noticed that my issue looks similar to this [issue](https://github.com/jaydenseric/graphql-upload/issues/218), but I didn't really understand if there were any fixes to that issue and if indeed it is the same issue I am facing. 

I tried to upgrade webpack (branch `upgraded-packages`) but this made the problem worse as I get this issue when I start the server

```
TypeError: Cannot read property 'graphql' of undefined
    at getPeerDependencyGraphQLRequirement (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:104216:44)
    at Object.ensureInstalledCorrectGraphQLPackage (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:104221:32)
    at Function.checkForErrors (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103346:27)
    at Function.generateFromMetadataSync (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103325:14)
    at Function.generateFromMetadata (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103315:29)
    at Object.buildSchema (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103940:61)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:99831:41
    at Generator.next (<anonymous>)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:99819:71
    at new Promise (<anonymous>)
    ```
    
   Any help would be greatly appreciated.

**Comment by jaydenseric** [comment]
> But then I build with webpack `yarn start` then run `yarn test` I get the following error

I cloned your repo, but there is no `yarn test` script…

**Comment by ziggy6792** [comment]
Hi @jaydenseric 

Thanks so much for such a detailed answer. 

Firstly, your experimental fix (`mainFields: ['main']`) for using webpack 4 works!
However, I get the strong impression from you that I should not be satisfied with that solution and it may lead to problems down the line.

Based on your recommendations, I tried the following setups;

- webpack 5 (branch name `webpack5`) got an error on `start` (looks like I am loosing my reflection stuff after bundling)

```
TypeError: Cannot read property 'graphql' of undefined
    at getPeerDependencyGraphQLRequirement (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:104216:44)
    at Object.ensureInstalledCorrectGraphQLPackage (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:104221:32)
    at Function.checkForErrors (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103346:27)
    at Function.generateFromMetadataSync (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103325:14)
    at Function.generateFromMetadata (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103315:29)
    at Object.buildSchema (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:103940:61)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:99831:41
    at Generator.next (<anonymous>)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:99819:71
    at new Promise (<anonymous>)
 ```

- webpack+esbuild  (branch name `webpack+esbuild`) got an error on `start`

```
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'firstName' of 'User' class.
    at Object.findType (webpack://type-graphql-series/./node_modules/type-graphql/dist/helpers/findType.js?:19:15)
    at eval (webpack://type-graphql-series/./node_modules/type-graphql/dist/decorators/Field.js?:16:53)
    at __decorateClass (webpack://type-graphql-series/./src/entity/User.ts?:13:24)
    at eval (webpack://type-graphql-series/./src/entity/User.ts?:24:1)
    at Module../src/entity/User.ts (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:3399:1)
    at __webpack_require__ (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:10636:42)
    at eval (webpack://type-graphql-series/./src/modules/user/Register.ts?:7:70)
    at Module../src/modules/user/Register.ts (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:3432:1)
    at __webpack_require__ (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:10636:42)
    at eval (webpack://type-graphql-series/./src/index.ts?:11:80)
[nodemon] app crashed - waiting for file changes before starting...
```

- esbuild (branch name `esbuild`) got an error on `start`

```
Same error as above
```

If you could provide anymore tips on getting webpack 5 or esbuild working that would be amazing. However I'm am sure these errors have got nothing to do with `graphql-upload` and I know you have better things to do than teach me how to use bundlers (and this not the right place this kind of support).

By the way the only reason I want to bundle in the first place is because I want to use 
- tsconfig paths
- absolute imports
- external dependencies as part of a larger mono-repo

Thanks so much for your support. You clearly know your stuff.

**Comment by ziggy6792** [comment]
Hey @jaydenseric

I worked it out with `esbuild` I just needed to use an extra plugin `@anatine/esbuild-decorators`

Thanks again for your help.

**Comment by rickklaasboer** [comment]
If anyone comes across this and wishes to still use Webpack (5). The fix is relatively simple. You could just [alias](https://webpack.js.org/configuration/resolve/#resolvealias) both imports for graphql/isobject.

```js
alias: {
    graphql$: path.resolve(
        __dirname,
        './node_modules/graphql/index.js',
    ),
    isobject$: path.resolve(
        __dirname,
        './node_modules/isobject/index.cjs.js',
    ),
},
```

**Comment by ziggy6792** [comment]
Hi @rickklaasboer 

Thanks for your input.
I would really like to get webpack5 working.

I tried your suggestion and pushed to branch [webpack5](https://github.com/ziggy6792/graphql-file-uploads/tree/webpack5)

```
resolve: {
      extensions: ['.mjs', '.ts', '.js'],
      alias: {
        graphql$: path.resolve(__dirname, './node_modules/graphql/index.js'),
        isobject$: path.resolve(__dirname, './node_modules/isobject/index.cjs.js'),
      },
      plugins: [
        new TsconfigPathsPlugin({
          /* options: see below */
        }),
      ],
    },
 ```
 
 However I still get the same error when I start
 
 ```
 TypeError: Cannot read property 'graphql' of undefined
    at getPeerDependencyGraphQLRequirement (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:115757:44)
    at Object.ensureInstalledCorrectGraphQLPackage (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:115762:32)
    at Function.checkForErrors (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:114887:27)
    at Function.generateFromMetadataSync (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:114866:14)
    at Function.generateFromMetadata (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:114856:29)
    at Object.buildSchema (/Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:115481:61)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:111372:41
    at Generator.next (<anonymous>)
    at /Users/sive/Documents/workspace/graphql-file-uploads/dist/index.js:111360:71
    at new Promise (<anonymous>)
```

Thanks

**Comment by rickklaasboer** [comment]
I've checked out your `webpack5` branch locally and it seems to be working just fine for me. Maybe try reinstalling your `node_modules`?

**Comment by ziggy6792** [comment]
Hmm this is weird.

I even recloned the whole project and I still get the error.
Is it a difference in node version maybe?

```
node -v
v15.11.0
yarn -v
1.22.10
```

I add a docker build and try reproduce the problem with any variables of our system taken out.
